M48
; DRILL file {KiCad (6.0.5)} date Thu Jun  2 01:50:44 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-02T01:50:44+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0984
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X4.5669Y-5.2165
X4.9606Y-4.3504
T2
X4.2323Y-5.1201
T3
X3.937Y-3.937
X3.937Y-5.1575
X5.1575Y-3.937
X5.1575Y-5.1575
T0
M30
